services:
  discord-echo-graph:
    container_name: echo-graph
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${FAST_API_PORT}:8000"
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"


