[supervisord]
nodaemon=true
logfile=/app/.logs/supervisord.log
logfile_maxbytes=5MB
loglevel=info

[program:api]
command=uvicorn src.api.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/.logs/api.log
stderr_logfile=/app/.logs/api.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB

[program:chatedubot]
command=python3 -m src.services.v1.ChatEdubot.educhat
directory=/app
autostart=true
autorestart=true
stdout_logfile=/app/.logs/chatedubot.log
stderr_logfile=/app/.logs/chatedubot.err.log
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB


